### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by ShozenD** [MLGlobalHealth/phyloSI-RakaiAgeGender#2]
**Tasks**

- [x] Change .yml name to “phyloSI-RakaiAgeGender”
- [x] README: in the Usage section, it is not clear if the aggregated data need to be generated first, and exactly how to do so (please add code chunks, ideally just one to generate all the aggregated data). Do this as in the updated Incidence section below.
- [x] README: Usage section, the incidence data should not be saved in the repo. Call the Rscript as I updated,
- [x] README: Usage section, transmission flows, please add the lines XYZ. Load the “phyloSI-RakaiAgeGender” if needed
