### ISSUE TITLE
Zenodo data repository

### ISSUE THREAD

**Issue by ShozenD** [MLGlobalHealth/phyloSI-RakaiAgeGender#5]
## TODO list
**Deadline:** ASAP  
- [x] Provide outputs for all Stan models for people without access the high-performance computing
- [x] Make sure scripts are compatible with the Zenodo download
- [x] Move all data in the GitHub repository to Zenodo
  - [x] RCCS surveillance analysis
  - [x] Deep Sequence Phylogenies
- [x] @abriz97 Populate deep_sequence_phylogenies
- [x] @ShozenD Populate RCCS surveillance directory
- [x] @ShozenD Make sure pre-processing scripts are compatible with Zenodo
- [x] @ShozenD Remove stage 2 preprocessing (viral load 200 is just a sensitivity analysis)
- [x] @ShozenD Run pre-processing steps and check run-time & output data size
- [x] @abriz97 Provide skeleton path specification file to @ShozenD
